config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboards#show'

  resources :reports, :bulksheets do
    post :import, on: :member
    post :analyze, on: :member
  end

  resources :search_terms, only: [:index, :show] do
    scope module: :search_terms do
      resources :stats, only: [] do
        collection do
          get :impressions, :clicks
        end
      end
    end
  end

  resources :ad_groups
  resources :campaigns
  resources :keywords, only: [:index, :show]
  resources :skus do
    scope module: :skus do
      resources :search_terms, only: :index
    end
  end
  resources :stats, only: [] do
    collection do
      get :impressions, :clicks, :spend, :sales
    end
  end

  resources :suggestions, only: :index
end

app/models/search_term.rb
class SearchTerm < ApplicationRecord
  scope :asin, -> { where(asin: true) }
  scope :customer_term, -> { where(asin: false) }

  has_many :search_term_report_items
  has_many :keywords,
    -> { positive.distinct },
    through: :search_term_report_items

  before_validation :check_if_asin

  scope :with_stats, lambda {
    select('
      search_terms.*,
      report_stats.*,
      CASE report_stats.impressions
        WHEN 0 THEN 0
        ELSE (report_stats.clicks::FLOAT / report_stats.impressions)
        END AS ctr,
      CASE report_stats.sales
        WHEN 0 THEN 0
        ELSE (report_stats.spend::FLOAT / report_stats.sales)
        END AS acos
      ')
      .joins('
        LEFT JOIN (
          SELECT search_term_id,
            SUM(impressions) AS impressions,
            SUM(clicks) AS clicks,
            SUM(spend) AS spend,
            SUM(seven_day_total_sales) AS sales,
            COUNT(*) AS reported_days
          FROM search_term_report_items
          GROUP BY search_term_id
        ) AS report_stats ON search_terms.id = report_stats.search_term_id
      ')
  }

  private

  def check_if_asin
    return unless text.present?
    self.asin = text.match?(/(b0)\w+/)
  end
end

app/models/sku.rb
class Sku < ApplicationRecord
  has_many :ads
  has_many :ad_groups, through: :ads
  has_many :keywords, through: :ad_groups
  has_many :campaigns, through: :ad_groups
  has_many :advertised_product_report_items

  has_many :search_terms,
    -> { distinct },
    through: :ad_groups

  has_many :customer_search_terms,
    -> { customer_term.distinct },
    through: :ad_groups,
    source: :search_terms

  has_many :related_asins,
    -> { asin.distinct },
    through: :ad_groups,
    source: :search_terms
end

app/controllers/search_terms/stats_controller.rb
module SearchTerms
  class StatsController < ApplicationController
    before_action :set_search_term

    def impressions
      render json: @search_term.search_term_report_items.group_by_day(:date).sum(:impressions)
    end

    def clicks
      render json: @search_term.search_term_report_items.group_by_day(:date).sum(:clicks)
    end

    private

    def set_search_term
      @search_term = SearchTerm.find(params[:search_term_id])
    end
  end
end

app/controllers/search_terms_controller.rb
class SearchTermsController < ApplicationController
  def index
    @search_terms = SearchTerm.with_stats.order('acos desc')
  end

  def show
    @search_term = SearchTerm.find(params[:id])
    @search_term_report_items = @search_term.search_term_report_items
    @keywords = @search_term.keywords.includes(ad_group: :campaign)
  end
end

app/controllers/skus/search_terms_controller.rb
module Skus
  class SearchTermsController < ApplicationController
    before_action :set_sku

    def index
      # @search_terms = @sku.customer_search_terms.with_stats_for_ad_group(@sku.ad_groups.pluck(:id))
      @search_terms = @sku.customer_search_terms.with_stats.order(:text)
    end

    private

    def set_sku
      @sku = Sku.find(params[:sku_id])
    end
  end
end

app/controllers/skus_controller.rb
class SkusController < ApplicationController
  before_action :set_sku, only: [:show, :edit, :update, :destroy]

  def index
    @skus = Sku.all
  end

  def show
    @ad_groups = @sku.ad_groups
    @search_terms = @sku.customer_search_terms
    @related_asins = @sku.related_asins
  end

  def new
    @sku = Sku.new
  end

  def edit; end

  def create
    @sku = Sku.new(sku_params)

    if @sku.save
      redirect_to @sku, notice: 'Sku was successfully created.'
    else
      render :new
    end
  end

  def update
    if @sku.update(sku_params)
      redirect_to @sku, notice: 'Sku was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @sku.destroy
    redirect_to skus_url, notice: 'Sku was successfully destroyed.'
  end

  private

  def set_sku
    @sku = Sku.find(params[:id])
  end

  def sku_params
    params.require(:sku).permit(:name, :asin)
  end
end

app/views/skus/search_terms/_search_term.html.erb
<tr>
  <td><%= link_to search_term.text, search_term_path(search_term) %></td>
  <td><%= search_term.reported_days %></td>
  <td><%= search_term.impressions %></td>
  <td><%= search_term.clicks %></td>
  <td><%= number_to_percentage(search_term.ctr * 100) if search_term.ctr %></td>
  <td><%= number_to_currency(search_term.spend / 100.0) if search_term.spend %></td>
  <td><%= number_to_currency(search_term.sales / 100.0) if search_term.sales %></td>
  <td><%= number_to_percentage(search_term.acos * 100) if search_term.acos %></td>
</tr>

app/views/skus/search_terms/index.html.erb
<%= breadcrumbs_helper([
  { text: 'Dashboard', path: root_path },
  { text: 'SKUs', path: skus_path },
  { text: @sku.name, path: sku_path(@sku) },
  { text: 'Search Terms', path: '' }
]) %>

<table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
  <thead>
    <tr>
      <th>Term</th>
      <th>Reported Days</th>
      <th>Impressions</th>
      <th>Clicks</th>
      <th>CTR</th>
      <th>Spend</th>
      <th>Sales</th>
      <th>ACoS</th>
    </tr>
  </thead>
  <tbody>
    <%= render @search_terms %>
  </tbody>
</table>