config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboards#show'

  resources :reports, :bulksheets do
    post :import, on: :member
    post :analyze, on: :member
  end

  resources :search_terms, only: [:index, :show] do
    scope module: :search_terms do
      resources :stats, only: [] do
        collection do
          get :impressions, :clicks
        end
      end
    end
  end

  resources :ad_groups
  resources :campaigns
  resources :keywords, only: [:index, :show]
  resources :skus do
    scope module: :skus do
      resources :search_terms, only: :index
    end
  end
  resources :stats, only: [] do
    collection do
      get :impressions, :clicks, :spend, :sales
    end
  end

  resources :suggestions, only: :index
end

app/models/search_term.rb
class SearchTerm < ApplicationRecord
  scope :asin, -> { where(asin: true) }
  scope :customer_term, -> { where(asin: false) }

  has_many :search_term_report_items
  has_many :keywords,
    -> { positive.distinct },
    through: :search_term_report_items

  before_validation :check_if_asin

  scope :with_stats, lambda {
    select('
      search_terms.*,
      report_stats.*,
      CASE report_stats.impressions
        WHEN 0 THEN 0
        ELSE (report_stats.clicks::FLOAT / report_stats.impressions)
        END AS ctr,
      CASE report_stats.sales
        WHEN 0 THEN 0
        ELSE (report_stats.spend::FLOAT / report_stats.sales)
        END AS acos
      ')
      .joins('
        LEFT JOIN (
          SELECT search_term_id,
            SUM(impressions) AS impressions,
            SUM(clicks) AS clicks,
            SUM(spend) AS spend,
            SUM(seven_day_total_sales) AS sales,
            COUNT(*) AS reported_days
          FROM search_term_report_items
          GROUP BY search_term_id
        ) AS report_stats ON search_terms.id = report_stats.search_term_id
      ')
  }

  private

  def check_if_asin
    return unless text.present?
    self.asin = text.match?(/(b0)\w+/)
  end
end

app/controllers/search_terms/stats_controller.rb
module SearchTerms
  class StatsController < ApplicationController
    before_action :set_search_term

    def impressions
      render json: @search_term.search_term_report_items.group_by_day(:date).sum(:impressions)
    end

    def clicks
      render json: @search_term.search_term_report_items.group_by_day(:date).sum(:clicks)
    end

    private

    def set_search_term
      @search_term = SearchTerm.find(params[:search_term_id])
    end
  end
end

app/controllers/search_terms_controller.rb
class SearchTermsController < ApplicationController
  def index
    @search_terms = SearchTerm.with_stats.order('acos desc')
  end

  def show
    @search_term = SearchTerm.find(params[:id])
    @search_term_report_items = @search_term.search_term_report_items
    @keywords = @search_term.keywords.includes(ad_group: :campaign)
  end
end

app/controllers/skus/search_terms_controller.rb
module Skus
  class SearchTermsController < ApplicationController
    before_action :set_sku

    def index
      # @search_terms = @sku.customer_search_terms.with_stats_for_ad_group(@sku.ad_groups.pluck(:id))
      @search_terms = @sku.customer_search_terms.with_stats.order(:text)
    end

    private

    def set_sku
      @sku = Sku.find(params[:sku_id])
    end
  end
end

app/views/search_terms/index.html.erb
<%= breadcrumbs_helper([
  { text: 'Dashboard', path: root_path },
  { text: 'Search Terms', path: search_terms_path }
]) %>

<table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
  <thead>
    <tr>
      <th>Term</th>
      <th>Reported Days</th>
      <th>Impressions</th>
      <th>Clicks</th>
      <th>CTR</th>
      <th>Spend</th>
      <th>Sales</th>
      <th>ACoS</th>
    </tr>
  </thead>
  <tbody>
    <%= render @search_terms %>
  </tbody>
</table>

app/views/search_terms/show.html.erb
<%= breadcrumbs_helper([
  { text: 'Dashboard', path: root_path },
  { text: 'Search Terms', path: search_terms_path },
  { text: @search_term.text, path: nil }
]) %>

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <p><strong>Search Term:</strong> <%= @search_term.text  %></p>
        <p><strong>First Recorded:</strong><%= @search_term.created_at.strftime('%b %d, %Y') %></p>
        <% if @search_term.asin? %>
          <p>
            <strong>ASIN</strong>
            <%= asin_link(@search_term.text) %>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="card mt-3">
      <div class="card-header">
        Triggered By Keywords
      </div>
      <div class="card-body">
        <ul class="list-group list-group-flush">
          <% @keywords.each do |keyword| %>
            <li class="list-group-item">
              <%= keyword.text %> <em><%= keyword.match_type %></em>
              <%= link_to keyword.ad_group.campaign.name, keyword.ad_group.campaign %>
              <%= link_to keyword.ad_group.name, keyword.ad_group %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="row mt-3">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        Impressions
      </div>
      <div class="card-body">
        <%= line_chart impressions_search_term_stats_path(@search_term) %>
      </div>
    </div>
  </div>

  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        Clicks
      </div>
      <div class="card-body">
        <%= line_chart clicks_search_term_stats_path(@search_term) %>
      </div>
    </div>
  </div>
</div>

<%= render partial: 'search_term_report_items/table', locals: { items: @search_term_report_items } %>