config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboards#show'

  resources :reports, :bulksheets do
    post :import, on: :member
    post :analyze, on: :member
  end

  resources :search_terms, only: [:index, :show] do
    scope module: :search_terms do
      resources :stats, only: [] do
        collection do
          get :impressions, :clicks
        end
      end
    end
  end

  resources :ad_groups
  resources :campaigns
  resources :keywords, only: [:index, :show]
  resources :skus do
    scope module: :skus do
      resources :search_terms, only: :index
    end
  end
  resources :stats, only: [] do
    collection do
      get :impressions, :clicks, :spend, :sales
    end
  end

  resources :suggestions, only: :index
end

app/models/report.rb
class Report < ApplicationRecord
  has_one_attached :file

  def self.importable?
    false
  end

  def importable?
    self.class.importable?
  end

  def analyzed?
    analyzed_at.present?
  end

  def imported?
    imported_at.present?
  end

  def filename
    file.blob.filename
  end

  def analyze!
    ReportAnalyzerService.new(self).call
  end

  def import!
    return unless
      importable? &&
      analyzed? &&
      file_format_valid? &&
      !imported?
    klass = (self.class.name + 'Importer').constantize
    klass.new(self).import!
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy, :import, :analyze]

  def index
    @reports = Report.all
  end

  def show; end

  def new
    @report = Report.new
  end

  def edit; end

  def create
    @report = Report.new(report_params)

    if @report.save
      redirect_to @report, notice: 'Report was successfully uploaded.'
    else
      render :new
    end
  end

  def update
    if @report.update(report_params)
      redirect_to @report, notice: 'Report was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @report.destroy
    redirect_to reports_url, notice: 'Report was successfully destroyed.'
  end

  def import
    @report.import!
    redirect_to @report.becomes(Report), notice: 'Report was successfully imported.'
  end

  def analyze
    @report.analyze!
    redirect_to @report.becomes(Report), notice: 'Report was successfully analyzed.'
  end

  private

  def set_report
    @report = Report.find(params[:id])
  end

  def report_params
    params.require(:report).permit(:file)
  end
end

app/views/reports/_form.html.erb
<%= simple_form_for(@report) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.file_field :file, direct_upload: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/reports/_report.html.erb
<tr>
  <td><%= link_to report.filename, report_path(report) %></td>
  <td><%= link_to 'Analyze', analyze_report_path(report), method: :post, class: 'btn btn-sm btn-primary' %></td>
  <td></td>
  <td></td>
</tr>

app/views/reports/index.html.erb
<%= breadcrumbs_helper([
  { text: 'Dashboard', path: root_path },
  { text: ' Reports', path: reports_path }
]) %>

<div class="row">
  <div class="col-md-12">
      <%= link_to 'Upload Report', new_report_path, class: 'btn btn-sm btn-success' %>
  </div>
</div>

<div class="row mt-3">
  <div class="col-md-12">
    <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
      <thead>
        <tr>
          <th>Name</th>
          <th>Type</th>
          <th>Period</th>
          <th>Imported</th>
        </tr>
      </thead>
      <tbody>
        <%= render @reports %>
      </tbody>
    </table>
  </div>
</div>

app/views/reports/new.html.erb
<%= render 'form' %>

app/views/reports/show.html.erb
<%= breadcrumbs_helper([
  { text: 'Dashboard', path: root_path },
  { text: 'Reports', path: reports_path },
  { text: @report.filename, path: nil }
]) %>

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header d-flex justify-content-between align-items-center">
        Report
        <div class="btn-group">
          <%= link_to 'Edit', edit_report_path(@report), class: 'btn btn-sm btn-secondary' %>
          <%= link_to 'Delete', report_path(@report), method: :delete, class: 'btn btn-sm btn-danger', data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
      <div class="card-body">
        <p>
          <strong>File:</strong>
          <%= link_to @report.file.blob.filename, rails_blob_path(@report.file, disposition: "attachment")  %>
        </p>
        <% if @report.analyzed? %>
          <p><strong>Type:</strong> <%= @report.type %></p>
          <% if @report.type == 'UnknownReport' %>
            <p><strong>Something is wrong with this report</strong></p>
          <% else %>
            <p><strong>Period:</strong> <%= @report.period_start.strftime('%b %d, %Y') %> - <%= @report.period_end.strftime('%b %d, %Y') %></p>
            <% if @report.imported? %>
              <p><strong>Imported:</strong> <%= @report.imported_at.strftime('%b %d, %Y') %></p>
            <% else %>
              <%= link_to 'Import Now', import_report_path(@report), method: :post, class: 'btn btn-primary' %>
            <% end %>
          <% end %>
        <% else %>
          <%= link_to 'Analyze Now', analyze_report_path(@report), method: :post, class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>